version: "2"
run:
  go: "1.22"
linters:
  default: all
  disable:
    - funcorder
    - exhaustruct
    - varnamelen
    - wrapcheck
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com
    lll:
      line-length: 140
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gochecknoglobals
        path: (.+)_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/bavix)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
